"""add summary and summarized_through_id to conversations

Revision ID: 343656317a6e
Revises: 77edd0808f9e
Create Date: 2026-09-23 06:20:06.691499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343656317a6e'
down_revision: Union[str, Sequence[str], None] = '77edd0808f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summarized_through_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summarized_through_id')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
